apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: rails-kube-app
spec:
  ports:
    - port: 3000
  selector:
    app: rails-kube-app
    tier: rails
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rails
spec:
  replicas: 1
  selector: 
    app: rails-kube-app
    tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: rails-kube-app
        tier: rails
    spec:
      containers:
      - name: rails
        image: tzumby/rails-app:v2.3
        args: ["bin/bundle exec rails s -p 3000 -b 0.0.0.0"]
        env:
        - name: REDIS_URL
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: RAILS_ENV
          value: development
        ports:
        - containerPort: 3000
