apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: tzumby/rails-app:latest
        args: ["rake db:create && rake db:migrate"]
        env:
        - name: RAILS_APP
          value: production
        - name: REDIS_URL
          value: redis
        - name: REDIS_PORT
          value: "6379"
      restartPolicy: Never
