apiVersion: v1
kind: ReplicationController
metadata:
  name: sidekiq
spec:
  replicas: 1
  selector: 
    app: rails-kube-app
    tier: sidekiq
  template:
    metadata:
      name: sidekiq
      labels:
        app: rails-kube-app
        tier: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: tzumby/rails-app:v2.3
        args: ["bin/bundle exec sidekiq -C config/sidekiq.yml"]
        env:
        - name: REDIS_URL
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: RAILS_ENV
          value: development
